name: Behat Tests

on:
  push:
    branches:
      - master
      - 'feature/**'
      - 'hotfix/**'
      - 'release/**'
  pull_request:
    branches:
      - master
      - 'feature/**'
      - 'hotfix/**'
      - 'release/**'

jobs:
  behat:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: greatfoods_test
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Create Database
      #   run: |
      #     mysql -uroot -h 127.0.0.1 --port 33306 -psecret -e "CREATE DATABASE greatfoods_test;"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: intl, opcache, pdo, pdo_mysql, zip
          coverage: none

      - name: Install dependencies
        run: composer install --no-ansi --no-interaction --no-progress --no-scripts --optimize-autoloader --no-suggest

      - name: Set up environment variables
        env:
          APP_ENV: test
          APP_SECRET: ${{ secrets.APP_SECRET }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          echo "APP_ENV=${APP_ENV}" >> $GITHUB_ENV
          echo "APP_SECRET=${APP_SECRET}" >> $GITHUB_ENV
          echo "DATABASE_URL=${DATABASE_URL}" >> $GITHUB_ENV
          echo "APP_ENV=${APP_ENV}" > .env
          echo "APP_SECRET=${APP_SECRET}" >> .env
          echo "DATABASE_URL=${DATABASE_URL}" >> .env
          echo "APP_ENV=${APP_ENV}" > .env.test
          echo "APP_SECRET=${APP_SECRET}" >> .env.test
          echo "DATABASE_URL=${DATABASE_URL}" >> .env.test

      - name: Create metadata directory
        run: mkdir -p config/serializer/v1

      - name: Run Migration
        run: |
          composer require --dev symfony/orm-pack
          php bin/console doctrine:schema:update --force || echo "No migrations found or schema update failed"
          php bin/console doctrine:migrations:migrate || echo "No migrations found or migration failed"
        env:
          DATABASE_URL: mysql://root:secret@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/greatfoods?serverVersion=8.0
      
      - name: Run behat tests
        run: ./vendor/bin/behat
